"""empty message

Revision ID: 4ef59b1c3327
Revises: fa79f366581c
Create Date: 2021-06-01 22:24:55.446832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef59b1c3327'
down_revision = 'fa79f366581c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('Artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['Venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id', 'Venue_id', 'Artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
